"""Compatibility wrapper for the auth service layer.

The actual runtime logic lives in backend.services.auth_service so the app can
import a stable module while the logic remains testable and decoupled from
startup-time env assumptions.
"""

from backend.services.auth_service import (
    ADMIN_EMAILS,
    ADMIN_ROLE,
    DEFAULT_ROLE,
    ROLE_PERMISSIONS,
    SESSION_COOKIE_NAME,
    SESSION_COOKIE_SECURE,
    SESSION_TTL_SECONDS,
    authenticate_user,
    clear_login_attempts,
    create_session,
    get_login_attempt_key,
    get_recent_events,
    get_session,
    get_user_permissions,
    get_user_role,
    init_db,
    invalidate_session,
    is_login_attempt_allowed,
    record_event,
    record_failed_login,
    register_user,
    require_permissions,
    require_roles,
    request_password_reset,
    reset_password,
    verify_admin,
    verify_otp,
    verify_session,
)

__all__ = [
    "ADMIN_EMAILS",
    "ADMIN_ROLE",
    "DEFAULT_ROLE",
    "ROLE_PERMISSIONS",
    "SESSION_COOKIE_NAME",
    "SESSION_COOKIE_SECURE",
    "SESSION_TTL_SECONDS",
    "authenticate_user",
    "clear_login_attempts",
    "create_session",
    "get_login_attempt_key",
    "get_recent_events",
    "get_session",
    "get_user_permissions",
    "get_user_role",
    "init_db",
    "invalidate_session",
    "is_login_attempt_allowed",
    "record_event",
    "record_failed_login",
    "register_user",
    "require_permissions",
    "require_roles",
    "request_password_reset",
    "reset_password",
    "verify_admin",
    "verify_otp",
    "verify_session",
]
